import type { Metadata } from "next"
import { Poppins } from "next/font/google"

import Player from "@/components/Player/Player"
import "@/styles/global.css"

import Providers from "./providers"

const font = Poppins({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
})

export const metadata: Metadata = {
  title: "Ajuricaba",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${font.className}`}>
        <Providers>
          {children}
          <Player />
        </Providers>
      </body>
    </html>
  )
}
